.travis.yml, Makefile
And make Travis call `make test` instead of `./run_tests.sh`
=> Add `make test` to bring inline with other repos

api/apps/predictions/views/helpers.py, api/apps/tide_gauges/serializers/raw_measurement_serializer.py, api/wsgi.py
Specifically E402 - see http://bugs.python.org/issue23061
=> Upate code for new PEP8

api/apps/ea_sea_levels/management/commands/convert_measurements.py, api/apps/predictions/management/commands/add_minute_for_each_prediction.py, api/apps/predictions/serializers/tide_window_serializer.py, api/apps/predictions/tests/views/test_helpers.py, api/apps/predictions/views/helpers.py, api/apps/status/views/observations.py, api/apps/status/views/tide_predictions.py, api/apps/tide_gauges/urls.py, api/libs/json_envelope_renderer/json_envelope_renderer.py, requirements/_testing.txt
These were brought into a new version of `flake8` so we should obey them
now.
=> Fix new PEP8 violations

api/libs/param_parsers/parse_time.py
This was left in after a copy and paste some time ago.
[Delivers #89624540]
=> Remove some dead code

HOWTO.md
Further commits to follow but I figured I'd get the ball rolling!
=> [WIP] HOWTO for putting data in the API

HOWTO.md
=> Further instructions on importing

api/apps/sea_levels/tests/views/test_permissions.py, api/apps/sea_levels/views/sea_levels.py
So that we can have non-public locations.
https://www.pivotaltracker.com/story/show/103299012
=> Use custom permissions in sea-levels endpoint

api/apps/status/templates/status/one_check_multiple_locations.html, api/apps/status/templates/status/one_check_single_location.html, api/apps/status/templates/status/status_all.html, api/apps/status/templates/status/status_index.html, api/template/rest_framework/api.html
Mixed content and external CSS providers, fully switch to HTTPS
=> Fix: The production API is hosted on https which throws a problem with

.gitignore, api/apps/predictions/tests/views/test_permissions.py, api/apps/predictions/tests/views/test_tide_window_class.py, api/apps/sea_levels/tests/views/test_permissions.py, api/apps/tide_gauges/tests/views/test_get_raw_measurements.py, api/apps/tide_gauges/tests/views/test_permissions.py, api/apps/users/helpers/__init__.py, api/apps/users/helpers/create_user.py, api/apps/users/tests/test_user_profile.py, api/libs/user_permissions/tests/test_permissions.py, pytest.ini, requirements/_testing.txt
pytest is an improved test runner compared to nose, mainly for development reasons.
The changes to tests are to make parallel tests to work.
=> Add pytest

functional_tests/test_root.py
=> Another pivotal test

.travis.yml, api/apps/predictions/urls.py, api/apps/predictions/views/weather.py, functional_tests/test_prediction_weather.py, requirements/_testing.txt
=> Weather: Test adding a selenium test

api/apps/observations/models/weather_observation.py, api/apps/observations/tests/views/test_weather.py, api/apps/predictions/models/weather_prediction.py, api/apps/predictions/tests/views/test_weather.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py
=> Weather sort by time

api/apps/observations/admin/__init__.py, api/apps/observations/admin/weather_observation_admin.py, api/apps/observations/urls.py, api/apps/predictions/admin/__init__.py, api/apps/predictions/admin/weather_prediction_admin.py, api/apps/predictions/urls.py
=> Weather add admin

api/apps/observations/models/weather_observation.py, api/apps/predictions/models/weather_prediction.py, functional_tests/test_prediction_weather.py
=> Weather: Add in additional range test, fix issues with ordering of

api/apps/observations/urls.py, api/apps/observations/views/weather.py, api/apps/predictions/views/weather.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py
=> Weather: Add in missing docs to API

api/apps/observations/migrations/0005_auto_20160414_1449.py, api/apps/observations/models/weather_observation.py, api/apps/observations/tests/views/test_weather.py, api/apps/predictions/migrations/0011_auto_20160414_1426.py, api/apps/predictions/models/weather_prediction.py, api/apps/predictions/tests/views/test_weather.py, api/libs/test_utils/weather.py, api/libs/view_helpers/rest_extensions.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py
=> Weather floats

api/apps/observations/models/weather_observation.py, api/apps/predictions/models/weather_prediction.py, api/apps/status/templates/status/status_index.html, api/apps/status/tests/views/test_weather_observations.py, api/apps/status/tests/views/test_weather_predictions.py, api/apps/status/urls.py, api/apps/status/views/__init__.py, api/apps/status/views/weather_observations.py, api/apps/status/views/weather_predictions.py, api/libs/test_utils/mixins.py, functional_tests/base.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py, functional_tests/test_status.py
=> Status weather api

.gitignore
Add in more patterns and separate out by category
=> More patterns for vim

api/apps/sea_levels/models/combined_prediction_observation.py, api/apps/sea_levels/tests/views/test_se_levels_latest.py, api/apps/sea_levels/urls.py, api/apps/sea_levels/views/__init__.py, api/apps/sea_levels/views/sea_levels_latest.py, functional_tests/test_sealevel.py
=> SeaLevels: Add in latest endpoint

api/apps/observations/admin/weather_observation_admin.py, api/apps/predictions/admin/weather_prediction_admin.py, functional_tests/base.py, functional_tests/base_weather.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py
=> Weather: Improve admin screens for weather

api/apps/users/serializers.py, api/apps/users/tests/test_authentication.py, api/apps/users/views/token.py, api/urls.py, functional_tests/test_authentication.py, functional_tests/test_status.py
=> Add in username/password auth

.travis.yml, Makefile, api/apps/notifications/tests/views/test_notification.py, api/apps/schedule/tests/views/test_schedule.py, api/apps/status/views/weather_observations.py, api/apps/status/views/weather_predictions.py, api/settings/development.py, api/settings/production.py, api/tests/test_api_root_view.py, functional_tests/base.py, functional_tests/test_observation_weather.py, functional_tests/test_prediction_weather.py, requirements/_common.txt, requirements/_production.txt
This will now mean we compile against 1.8 - 1.9
=> Django - New versions for travis to tests

functional_tests/base.py, functional_tests/test_prediction_weather.py, functional_tests/test_status.py, requirements/_common.txt
=> Selenium: Firefox 44 is the current max supported version, support

api/apps/tide_gauges/serializers/raw_measurement_serializer.py, api/apps/tide_gauges/tests/views/test_post_raw_measurements.py, api/apps/tide_gauges/views/raw_measurements.py
=> Fix Bug: Common issue with accessing front end api endpoint for

api/apps/tide_gauges/tests/views/test_raw_measurements_metadata.py, api/apps/tide_gauges/views/raw_measurements.py
=> Fix: Remove server error when the user provides a bad location, returns
